simulation:
  terrain: "plane"
  camera: False
  lateralFriction: 1.0
  spinningFriction: 0.0065
  freq: 500.0
  stand_kp: 100.0
  stand_kd: 1.0
  joint_kp: 0.0
  joint_kd: 0.05
robot:
  freq: 500.0
  stand_kp: 100.0
  stand_kd: 1.0
  joint_kp: 10.0
  joint_kd: 0.2
### add by shimizu
communication:
  divide: 1
  use_position_control: True
mpc :
  iterations_between_mpc: 13 ### mpc Hz = freq/(divide*this)
  horizonLength: 14
estimator:
  dt: 0.002 ### = 1/freq * divide



